

-- EJERCICIO 2 V_SALDOS_INDIVIDUAL FUNCIONA :D

CREATE OR REPLACE VIEW V_SALDOS_INDIVIDUAL AS
    SELECT CLIENTE.IDENTIFICACION, CUENTA_FINTECH.IBAN,DEPOSITADA_EN.SALDO,DIVISA.ABREVIATURA,DIVISA.CAMBIOEURO
    FROM CLIENTE JOIN CUENTA_FINTECH ON CLIENTE.ID=CUENTA_FINTECH.CLIENTE_ID 
    JOIN DEPOSITADA_EN ON DEPOSITADA_EN.POOLED_ACCOUNT_IBAN=CUENTA_FINTECH.IBAN 
    JOIN CUENTA_REFERENCIA ON CUENTA_REFERENCIA.IBAN=DEPOSITADA_EN.CUENTA_REFERENCIA_IBAN
    JOIN DIVISA ON CUENTA_REFERENCIA.DIVISA_ABREVIATURA=DIVISA.ABREVIATURA
    
    UNION ALL
    
    SELECT CLIENTE.IDENTIFICACION, CUENTA_FINTECH.IBAN,CUENTA_REFERENCIA.SALDO,DIVISA.ABREVIATURA,DIVISA.CAMBIOEURO
    FROM CLIENTE JOIN CUENTA_FINTECH ON CLIENTE.ID=CUENTA_FINTECH.CLIENTE_ID 
    JOIN CUENTA_REFERENCIA ON CUENTA_REFERENCIA.IBAN=CUENTA_FINTECH.IBAN
    JOIN DIVISA ON CUENTA_REFERENCIA.DIVISA_ABREVIATURA=DIVISA.ABREVIATURA;
    
CREATE OR REPLACE VIEW V_SALDOS_AUTORIZADA AS
    SELECT PERSONA_AUTORIZADA.IDENTIFICACION, CUENTA_FINTECH.IBAN,DEPOSITADA_EN.SALDO,DIVISA.ABREVIATURA,DIVISA.CAMBIOEURO
    FROM PERSONA_AUTORIZADA JOIN AUTORIZACION ON AUTORIZACION.PERSONA_ID=PERSONA_AUTORIZADA.ID
    JOIN EMPRESA ON AUTORIZACION.EMPRESA_ID=EMPRESA.ID
    JOIN CLIENTE ON CLIENTE.ID=EMPRESA.ID
    JOIN CUENTA_FINTECH ON CLIENTE.ID=CUENTA_FINTECH.CLIENTE_ID 
    JOIN DEPOSITADA_EN ON DEPOSITADA_EN.POOLED_ACCOUNT_IBAN=CUENTA_FINTECH.IBAN 
    JOIN CUENTA_REFERENCIA ON CUENTA_REFERENCIA.IBAN=DEPOSITADA_EN.CUENTA_REFERENCIA_IBAN
    JOIN DIVISA ON CUENTA_REFERENCIA.DIVISA_ABREVIATURA=DIVISA.ABREVIATURA
    
    UNION ALL
    
    SELECT PERSONA_AUTORIZADA.IDENTIFICACION, CUENTA_FINTECH.IBAN,CUENTA_REFERENCIA.SALDO,DIVISA.ABREVIATURA,DIVISA.CAMBIOEURO
     FROM PERSONA_AUTORIZADA JOIN AUTORIZACION ON AUTORIZACION.PERSONA_ID=PERSONA_AUTORIZADA.ID
    JOIN EMPRESA ON AUTORIZACION.EMPRESA_ID=EMPRESA.ID
    JOIN CLIENTE ON CLIENTE.ID=EMPRESA.ID
    JOIN CUENTA_FINTECH ON CLIENTE.ID=CUENTA_FINTECH.CLIENTE_ID 
    JOIN CUENTA_REFERENCIA ON CUENTA_REFERENCIA.IBAN=CUENTA_FINTECH.IBAN
    JOIN DIVISA ON CUENTA_REFERENCIA.DIVISA_ABREVIATURA=DIVISA.ABREVIATURA;

--EJERCICIO 2 TR_TRANSACCION

CREATE SEQUENCE SQ_TRANSACCION
    START WITH 1; --SI YA HAY DATOS EN TRANSACCION CAMBIAR A UN NUMERO QUE NO TENGA YA ID_UNICA

CREATE OR REPLACE TRIGGER TR_TRANSACCION
    BEFORE INSERT ON TRANSACCION
        FOR EACH ROW
Begin
    :new.ID_UNICO := SQ_TRANSACCION.NEXTVAL;
END TR_TRANSACCION;

--EJERCICIO 3 A) V_TARJETA_MENSUAL

CREATE OR REPLACE VIEW V_TARJETA_MENSUAL (IDENTIFICACION, NUMERO_TARJETA, GASTO, ABREVIATURA) 
    AS (SELECT CLIENTE.identificacion, TARJETA_CREDITO.num_tarjeta, SUM(MOVIMIENTO.cantidad), DIVISA.abreviatura 
    FROM CLIENTE, DIVISA, TARJETA_CREDITO, MOVIMIENTO, CUENTA_FINTECH
    
    WHERE
        CUENTA_FINTECH.CLIENTE_ID=CLIENTE.ID AND
        CUENTA_FINTECH.IBAN = TARJETA_CREDITO.CUENTA_IBAN AND
        TARJETA_CREDITO.num_tarjeta = MOVIMIENTO.num_tarjeta AND
        MOVIMIENTO.divisa = DIVISA.abreviatura
    GROUP BY DIVISA.abreviatura,CLIENTE.identificacion, TARJETA_CREDITO.num_tarjeta);

-- =========================OPCIONAL===================
-- 4. AUDITORÍAS
AUDIT ALL ON FINTECH.TRANSACCION;
AUDIT ALL ON FINTECH.MOVIMIENTO;

AUDIT UPDATE, INSERT, DELETE ON FINTECH.DEPOSITADA_EN;
AUDIT UPDATE, INSERT, DELETE ON FINTECH.CUENTA_REFERENCIA;

---- DESDE SYSTEM --
--Muestra la auditoría estándar:
SELECT * FROM SYS.DBA_AUDIT_TRAIL;

--Información relativa a la auditoría de los inicios de sesión de los usuarios
SELECT * FROM SYS.DBA_AUDIT_SESSION;

-- Ver que la auditoría AUDIT_TRAIL está activa:
SELECT name, value
FROM v$parameter
WHERE NAME LIKE 'audit_trail';
-- ====FIN AUDITORÍAS====

