-- ROLES

CREATE ROLE R_PERSONAL; -- admin
CREATE ROLE R_USUARIO;
CREATE ROLE R_PERS_AUT; -- Introducir y borrar cuentas

GRANT CONNECT TO R_PERSONAL, R_USUARIO, R_PERS_AUT;-- SE PUEDEN CONECTAR
GRANT EXECUTE ON PK_GESTION_CLIENTES TO R_PERSONAL;-- EL PERSONAL PUEDE MANIPULAR LOS CLIENTES/PERSONAS AUTORIZADAS
GRANT EXECUTE ON PK_GESTION_CUENTAS TO R_PERSONAL, R_PERS_AUT;--EL PERSONAL Y LAS PERSONAS AUTORIZADAS PUEDEN MANIPULAR LAS CUENTAS

GRANT SELECT ON CLIENTE TO R_USUARIO, R_PERS_AUT;--TODOS LOS USUARIOS PUEDEN ACCEDER A LA INFORMACION NECESARIA
GRANT SELECT ON EMPRESA TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON INDIVIDUAL TO R_USUARIO;
GRANT SELECT ON CUENTA_FINTECH TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON CUENTA_POOLED TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON SEGREGADA TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON REFERENCIA TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON TARJETA_CREDITO TO R_USUARIO, R_PERS_AUT;
GRANT SELECT ON MOVIMIENTO TO R_USUARIO, R_PERS_AUT;

GRANT SELECT ON DEPOSITADA_EN TO R_PERS_AUT;
GRANT SELECT ON DIVISA TO R_PERS_AUT;

GRANT SELECT ANY TABLE TO R_PERSONAL;

GRANT EXECUTE ON PK_GESTION_CLIENTES TO R_PERSONAL, R_PERS_AUT;
GRANT EXECUTE ON PK_GESTION_CUENTAS TO R_PERSONAL, R_PERS_AUT;
GRANT SELECT ON V_SALDOS_INDIVIDUAL TO R_USUARIO, R_PERSONAL, R_PERS_AUT;
GRANT SELECT ON V_SALDOS_AUTORIZADA TO R_USUARIO, R_PERSONAL, R_PERS_AUT;
GRANT SELECT ON V_TARJETA_MENSUAL TO R_USUARIO, R_PERSONAL, R_PERS_AUT;
GRANT SELECT ON V_PAGOS_PENDIENTES TO R_USUARIO, R_PERSONAL, R_PERS_AUT;
GRANT EXECUTE ON P_COBROS TO PERSONAL, R_PERS_AUT;

--USUARIOS

CREATE USER usuario1 IDENTIFIED BY user01;
GRANT R_USUARIO TO usuario1;

CREATE USER personal IDENTIFIED BY personal01;
GRANT R_PERSONAL TO personal;

CREATE USER persAut IDENTIFIED BY pa01;
GRANT R_PERS_AUT TO persAut;